
services:
  db:
    container_name: school-db
    image: postgres:15
    networks:
      - school-backend
    environment:
      - POSTGRES_DB=school
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 4321:5432
    volumes:
        - school_db_data:/var/lib/postgresql/data

  server:
    container_name: school-api
    image: school-server:latest
    environment:
      - DATABASE_URL=postgresql://root:mysecretpassword@localhost:4321/school?sslmode=disable
      - OAUTH_CLIENT_ID=688282033704-2leacl36je751emdajmd7n2c8u3gnqrs.apps.googleusercontent.com
      - OAUTH_SECRET=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
      - REDIRECT_URL=http://127.0.0.1:8080/auth/sessions/google
      - RANDOM_KEY=be11e551-6c13-419a-a1f2-cb8f6cf476d4
      - JWT_MAX_AGE=48
      - RUST_LOG=simple-auth-server=debug,actix_web=info,actix_server=info
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    build:
      context: .
      network: host
    networks:
      - school-backend
    ports:
      - 8080:8080
    depends_on:
      - db


networks:
  school-backend:
    driver: bridge

volumes:
  school_db_data: {}