
services:
  db:
    container_name: school-db
    image: postgres:15
    networks:
      - school-backend
    environment:
      - POSTGRES_DB=school
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 4321:5432
    volumes:
        - school_db_data:/var/lib/postgresql/data

  server:
    container_name: school-api
    image: school-server:latest
    env_file:
      - dev.env
    build:
      context: .
      network: host
    networks:
      - school-backend
    ports:
      - 8080:8080
    depends_on:
      - db


networks:
  school-backend:
    driver: bridge

volumes:
  school_db_data: {}