services:
  db:
    container_name: school-db-prod
    image: postgres:15
    networks:
      - school-backend-prod
    environment:
      - POSTGRES_DB=school
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 5432:5432
    volumes:
      - school_db_volume:/var/lib/postgresql/data

  server:
    container_name: school-api-prod
    image: school-api-prod:0.2.0
    build:
      context: .
      network: host
    environment:
      - DATABASE_URL=${DATABASE_URL_PROD}
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - OAUTH_SECRET=${OAUTH_SECRET}
      - REDIRECT_URL=${REDIRECT_URL}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - school-backend-prod
    ports:
      - 8080:8080
    depends_on:
      - db
    entrypoint:
      [
        "/school-api/wait-for.sh",
        "school-db-prod:5432",
        "--",
        "/school-api/start.sh",
      ]
    command: ["/school-api/server"]

networks:
  school-backend-prod:
    driver: bridge

volumes:
  school_db_volume: {}
