
services:
  server:
    env_file:
      - dev.env
    build:
      context: .
      target: final
    image: school-server:latest
    networks:
      - school-backend
    ports:
      - 8080:8080



networks:
  school-backend:
    driver: bridge