services:
  db:
    container_name: school-db-prod
    image: postgres:15
    networks:
      - school-backend-prod
    environment:
      - POSTGRES_DB=school
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 4321:5432
    volumes:
      - school_db_data:/var/lib/postgresql/data

  server:
    container_name: school-api
    image: school-server:latest
    env_file:
      - dev.env
    build:
      context: .
      network: host
    # NEEDED ENV VARS
    environment:
    #   - DATABASE_URL="postgres://root:mysecretpassword@school-db-prod/school"
    #   - OAUTH_CLIENT_ID=""
    #   - OAUTH_SECRET=""
    #   - REDIRECT_URL=""
    #   - RANDOM_KEY=""
    #   - JWT_MAX_AGE=48
    #   - RUST_LOG='simple-auth-server=debug,actix_web=info,actix_server=info'
    networks:
      - school-backend-prod
    ports:
      - 8080:8080
    depends_on:
      - db
    entrypoint:
      ["/bin/wait-for.sh", "school-db-prod:5432", "--", "/bin/start.sh"]
    command: ["/bin/server"]

networks:
  school-backend-prod:
    driver: bridge

volumes:
  school_db_data: {}
